import ky from 'ky'
import type {
  Agent,
  AgentType,
  AgentLog,
  AgentSpawnRequest,
  AgentStatsResponse,
  RunningAgent,
  Task,
  CreateTaskRequest,
  UpdateTaskRequest,
  Message,
  Project,
  Blueprint,
  Pipeline,
  PipelineRun,
  PipelineRunRequest,
  StepRun,
  FileChange,
  DirListing,
  SendMessageRequest,
  SendMessageResponse,
  SendFollowUpRequest,
  SendFollowUpResponse,
} from '@metronome/types'

const http = ky.create({ prefixUrl: '/api' })

export const api = {
  fs: {
    list: (dirPath: string) => http.get('fs/list', { searchParams: { path: dirPath } }).json<DirListing>(),
  },
  agents: {
    list: () => http.get('agents').json<Agent[]>(),
    types: () => http.get('agents/types').json<AgentType[]>(),
    availability: () => http.get('agents/availability').json<Record<string, boolean>>(),
    running: () => http.get('agents/running').json<RunningAgent[]>(),
    get: (id: string) => http.get(`agents/${id}`).json<Agent>(),
    logs: (id: string) => http.get(`agents/${id}/logs`).json<AgentLog[]>(),
    spawn: (body: AgentSpawnRequest) => http.post('agents/spawn', { json: body }).json<{ agentId: string }>(),
    kill: (id: string) => http.delete(`agents/${id}`),
    stats: () => http.get('agents/stats').json<AgentStatsResponse>(),
    resume: (id: string, prompt: string) => http.post(`agents/${id}/resume`, { json: { prompt } }).json<{ agentId: string }>(),
  },
  tasks: {
    list: (projectId?: string) => http.get('tasks', { searchParams: projectId ? { project_id: projectId } : {} }).json<Task[]>(),
    get: (id: string) => http.get(`tasks/${id}`).json<Task>(),
    subtasks: (id: string) => http.get(`tasks/${id}/subtasks`).json<Task[]>(),
    messages: (id: string) => http.get(`tasks/${id}/messages`).json<Message[]>(),
    create: (body: CreateTaskRequest) => http.post('tasks', { json: body }).json<{ id: string }>(),
    update: (id: string, body: UpdateTaskRequest) => http.patch(`tasks/${id}`, { json: body }).json<Task>(),
    delete: (id: string) => http.delete(`tasks/${id}`),
  },
  projects: {
    list: () => http.get('projects').json<Project[]>(),
    create: (body: { name: string; path: string }) => http.post('projects', { json: body }).json<{ id: string }>(),
    delete: (id: string) => http.delete(`projects/${id}`),
  },
  blueprints: {
    list: () => http.get('blueprints').json<Blueprint[]>(),
    get: (name: string) => http.get(`blueprints/${name}`).json<Blueprint>(),
    save: (name: string, body: Blueprint) => http.put(`blueprints/${name}`, { json: body }).json<Blueprint>(),
    delete: (name: string) => http.delete(`blueprints/${name}`),
  },
  pipelines: {
    list: () => http.get('pipelines').json<Array<Pipeline & { source: string }>>(),
    get: (name: string) => http.get(`pipelines/${name}`).json<Pipeline>(),
    run: (name: string, body: PipelineRunRequest) => http.post(`pipelines/${name}/run`, { json: body }).json<{ runId: string }>(),
    runDynamic: (body: PipelineRunRequest) => http.post('pipelines/run-dynamic', { json: body }).json<{ runId: string }>(),
    requestReplan: (id: string) => http.post(`pipelines/runs/${id}/replan`).json<{ ok: boolean }>(),
    listRuns: (projectId?: string) => http.get('pipelines/runs', { searchParams: projectId ? { project_id: projectId } : {} }).json<PipelineRun[]>(),
    cancelRun: (id: string) => http.post(`pipelines/runs/${id}/cancel`).json<{ ok: boolean }>(),
    approveStep: (runId: string, stepId: string) => http.post(`pipelines/runs/${runId}/approve/${stepId}`).json<{ ok: boolean }>(),
    rejectStep: (runId: string, stepId: string) => http.post(`pipelines/runs/${runId}/reject/${stepId}`).json<{ ok: boolean }>(),
    getRun: (id: string) => http.get(`pipelines/runs/${id}`).json<PipelineRun>(),
    getRunSteps: (id: string) => http.get(`pipelines/runs/${id}/steps`).json<StepRun[]>(),
    getRunFiles: (id: string) => http.get(`pipelines/runs/${id}/files`).json<FileChange[]>(),
  },
  chat: {
    send: (body: SendMessageRequest) => http.post('chat', { json: body }).json<SendMessageResponse>(),
    message: (body: SendFollowUpRequest) => http.post('chat/message', { json: body }).json<SendFollowUpResponse>(),
    messages: (taskId: string) => http.get(`chat/messages/${taskId}`).json<Message[]>(),
  },
}
